Repository mozilla/perfcompare, pull requests merged in 2024-12, with the labels that each got.

#803 PCF-549 Add the name of the device used instead of just "Android"
  src/__tests__/CompareResults/RevisionRow.test.tsx
  src/__tests__/utils/platform.test.ts
  src/components/CompareResults/RevisionRow.tsx
  src/utils/platform.ts
Labels: Ready For Review

#811 Update perfcompare doc link in ReadME
  README.md
Labels: Ready For Review

#800 PCF-323 Expanded row doesn't match the figma design
  src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
  src/components/CompareResults/RevisionRow.tsx
  src/components/CompareResults/RevisionRowExpandable.tsx
  src/components/CompareResults/SubtestsResults/SubtestsRevisionRow.tsx
Labels: Ready For Review

#798 PCF-524 Display the mean instead of the median in the results table rows + update the column title + display median in the expanded row as well
  src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
  src/__tests__/utils/fixtures.ts
  src/components/CompareResults/Distribution.tsx
  src/components/CompareResults/RevisionRow.tsx
  src/components/CompareResults/RevisionRowExpandable.tsx
  src/components/CompareResults/RunValues.tsx
  src/mockData/9d50665254899d8431813bdc04178e6006ce6d59.ts
  src/mockData/a998c42399a8fcea623690bf65bef49de20535b4.ts
  src/mockData/bb6a5e451dace3b9c7be42d24c9272738d73e6db.ts
  src/types/state.ts
Labels: Resolved Comments / Re-Review

#813 Slightly simplify the implementation of processResults for subtests
  src/components/CompareResults/SubtestsResults/SubtestsResultsTable.tsx
Labels: Ready For Review

#812 Adjust table styles and alignments
  src/__tests__/CompareResults/ResultsView.test.tsx
  src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
  src/components/CompareResults/ResultsTable.tsx
  src/components/CompareResults/RevisionRow.tsx
  src/components/CompareResults/RevisionRowExpandable.tsx
  src/components/CompareResults/SubtestsResults/SubtestsResultsTable.tsx
  src/components/CompareResults/SubtestsResults/SubtestsRevisionRow.tsx
  src/components/CompareResults/SubtestsResults/SubtestsTableContent.tsx
  src/components/CompareResults/TableHeader.tsx
  src/styles/ExpandableRow.ts
  src/styles/index.tsx
Labels: Ready For Review

#821 PCF-582 PerfCompare link in the graphs view fails with: Error: r[0] is undefined
  src/__tests__/CompareResults/SubtestsResultsView.test.tsx
  src/__tests__/utils/fixtures.ts
  src/components/CompareResults/SubtestsResults/SubtestsResultsMain.tsx
Labels: Ready For Review

#818 PCF-576 Add checkboxes to the table filters dropdown
  src/components/CompareResults/TableHeader.tsx
Labels: Ready For Review

#817 Make dark mode readable for subtests status
  src/__tests__/CompareResults/SubtestsRevisionRow.test.tsx
  src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/SubtestsRevisionRow.test.tsx.snap
  src/__tests__/utils/fixtures.ts
  src/components/CompareResults/RevisionRow.tsx
  src/components/CompareResults/SubtestsResults/SubtestsRevisionRow.tsx
  src/styles/Colors.ts
  src/theme/protocolTheme.ts
Labels: 🚧 WIP 🚧, Ready For Review

#827 Update fixture header_name
  src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
  src/__tests__/utils/fixtures.ts
Labels: Ready For Review

#822 add input background color to select input when focused
  src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/RevisionSelect.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
  src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
  src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
  src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
  src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
  src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
  src/__tests__/__snapshots__/App.test.tsx.snap
  src/components/Shared/FrameworkDropdown.tsx
  src/styles/DropDownMenu.ts
  src/styles/Select.ts
  src/theme/components.js
Labels: Ready For Review, Changes Requested

#825 Allow text copying from the edit revision panel
  src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
  src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
  src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
  src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
  src/__tests__/Search/__snapshots__/SelectedRevision.test.tsx.snap
  src/components/Search/SelectedRevisionItem.tsx
  src/styles/SelectedRevsStyle.ts
Labels: Ready For Review

#834 Add a new palette property for the buttons inside the table header
  src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
  src/components/CompareResults/TableHeader.tsx
  src/theme/protocolTheme.ts
Labels: Ready For Review

#829 Silence the warning generated by the Breadcrumbs component by inserting a span instead of a fragment
  src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
  src/components/CompareResults/SubtestsResults/SubtestsBreadcrumbs.tsx
Labels: Ready For Review
