Repository mozilla/perfcompare, pull requests merged in 2025-05, with the labels that each got.

#882 Change how the filters are implemented so that the behavior is a bit better
  src/__tests__/CompareResults/ResultsTable.test.tsx
  src/components/CompareResults/TableHeader.tsx
  src/hooks/useTableFilters.ts
Labels: Ready For Review

#879 Bug 1962486 - Optimize and create new perfcompare loader
  src/__tests__/Search/fetchRevisionFromHash.test.tsx
  src/components/App.tsx
  src/components/CompareResults/ResultsView.tsx
  src/components/CompareResults/hashToCommitLoader.ts
  src/components/CompareResults/loader.ts
  src/logic/treeherder.ts
Labels: Changes Requested

#884 Add ability to compare commits from ./mach try perf with lando ids
  src/__tests__/Search/fetchRevisionFromLando.test.tsx
  src/components/App.tsx
  src/components/CompareResults/ResultsView.tsx
  src/components/CompareResults/hashToCommitLoader.ts
  src/components/CompareResults/landoToCommitLoader.ts
  src/logic/lando.ts
  src/logic/treeherder.ts
  src/types/state.ts
Labels: Ready For Review

#865 Update Search to use `search` and `hash`
  src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
  src/__tests__/Search/SearchView.test.tsx
  src/__tests__/Search/SelectedRevision.test.tsx
  src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
  src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
  src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
  src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
  src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
  src/__tests__/Search/fetchRevisionsBySearch.test.tsx
  src/__tests__/utils/fixtures.ts
  src/components/Search/SearchInputAndResults.tsx
  src/logic/treeherder.ts
  src/resources/Strings.tsx
Labels: priority: high, Ready For Review

#886 Update build-related packages
  package-lock.json
  package.json
  webpack/webpack.common.js
  webpack/webpack.development.js
Labels: Ready For Review

#889 In the tests for SubtestsRevisionRow, wait until the page is rendered before asserting
  src/__tests__/CompareResults/SubtestsRevisionRow.test.tsx
  src/__tests__/CompareResults/__snapshots__/SubtestsRevisionRow.test.tsx.snap
Labels: Ready For Review

#877 PCF-523 Results table: add nowrap to tags list
  src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
  src/components/CompareResults/LinkToRevision.tsx
  src/components/CompareResults/TestHeader.tsx
Labels: Ready For Review
