Repository mozilla/perfcompare, pull requests merged in 2025-02, with the labels that each got.

#844 PCF-561 When there are a lot of replicates, the expanded row with all the runs is too long
  src/__tests__/CompareResults/RevisionRow.test.tsx
  src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
  src/__tests__/utils/fixtures.ts
  src/components/CompareResults/RunValues.tsx
Labels: Ready For Review

#851 Add tooltip to subtests page
  src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
  src/components/CompareResults/SubtestsResults/SubtestsResultsTable.tsx
Labels: Approved

#856 Increase `lineHeight` to `1.5`
  src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/SubtestsRevisionRow.test.tsx.snap
  src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
  src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
  src/__tests__/Search/__snapshots__/SearchContainer.test.tsx.snap
  src/__tests__/Search/__snapshots__/SearchResultsList.test.tsx.snap
  src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
  src/__tests__/Search/__snapshots__/SelectedRevision.test.tsx.snap
  src/__tests__/TaskclusterAuth/__snapshots__/TaskclusterCallback.test.tsx.snap
  src/__tests__/__snapshots__/App.test.tsx.snap
  src/components/CompareResults/LinkToRevision.tsx
  src/components/CompareResults/ResultsMain.tsx
  src/components/CompareResults/RevisionRow.tsx
  src/components/CompareResults/SubtestsResults/SubtestsRevisionHeader.tsx
  src/components/CompareResults/SubtestsResults/SubtestsRevisionRow.tsx
  src/components/CompareResults/TableHeader.tsx
  src/components/CompareResults/TestHeader.tsx
  src/styles/Fonts.ts
  src/styles/SelectList.ts
  src/styles/SelectedRevsStyle.ts
  src/theme/components.js
  src/theme/typography.ts
Labels: Changes Requested

#854 add zindex to filter menu
  src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
  src/components/CompareResults/TableHeader.tsx
Labels: Approved

#841 Add a copy icon to easily copy revisions
  src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
  src/__tests__/Search/SelectedRevision.test.tsx
  src/__tests__/Search/__snapshots__/CompareOverTime.test.tsx.snap
  src/__tests__/Search/__snapshots__/CompareWithBase.test.tsx.snap
  src/__tests__/Search/__snapshots__/SearchView.test.tsx.snap
  src/__tests__/Search/__snapshots__/SelectedRevision.test.tsx.snap
  src/components/CompareResults/LinkToRevision.tsx
  src/components/Search/SelectedRevisionItem.tsx
  src/components/Shared/CopyIcon.tsx
Labels: Approved

#860 Fix incorrectly rendered platform on results table
  src/__tests__/CompareResults/ResultsTable.test.tsx
  src/__tests__/CompareResults/RevisionRow.test.tsx
  src/__tests__/CompareResults/__snapshots__/OverTimeResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsTable.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
  src/components/CompareResults/TableContent.tsx
  src/utils/platform.ts
Labels: Approved

#859 Follow up PCF-561 Add copy run values to extended row
  src/__tests__/CompareResults/RevisionRow.test.tsx
  src/__tests__/CompareResults/__snapshots__/ResultsView.test.tsx.snap
  src/components/CompareResults/RunValues.tsx
Labels: Ready For Review

#863 Fix alignment for long test name in subtest revision row
  src/__tests__/CompareResults/__snapshots__/SubtestsResultsView.test.tsx.snap
  src/__tests__/CompareResults/__snapshots__/SubtestsRevisionRow.test.tsx.snap
  src/components/CompareResults/SubtestsResults/SubtestsRevisionRow.tsx
Labels: Approved
